version: "1.0"
info:
  model: int-scaffold
services:
- serviceName: edge.pc_newgit.integrations:getBiodata
  packages:
  - name: EdgePC_NewGit
    version: "1.0"
- serviceName: edge.pc_newgit.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:getCustomerByID
  packages:
  - name: EdgePC_NewGit
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.560
- serviceName: edge.pc_newgit.integrations:getBiodataByID2
  packages:
  - name: EdgePC_NewGit
    version: "1.0"
packages:
- name: EdgePC_NewGit
  gitServerName: PC_github
  gitUrl: https://github.com/pchew999/EdgePC_NewGit
  gitUsername: pchew999
  gitToken: edge.scaffolding.EdgePC_NewGit.PC_github.gitToken
  gitBranch: main
